### ISSUE TITLE
Full screen is hiding browser's address bar ( output screen )

### ISSUE THREAD

**Issue by santup** [varemenos/codemagic#74]
I think, most users want to test their code in live mode, means they want to look their output as how it looks in browser ( with addressbar ). at least for OUTPUT white screen, it should not hide address bar.

**Comment by varemenos** [comment]
I'm sorry but the fullscreen feature utilizes the fullscreen API of the browser, and that indicates that in the screen the only thing displayed is the result.

You can instead hide the editors by using this button:

![screenshot from 2015-02-01 03 29 08](https://cloud.githubusercontent.com/assets/626343/5990629/84d9b62a-a9c2-11e4-9dd0-773ca2b1b5e3.png)
