### ISSUE TITLE
Install Instructions?

### ISSUE THREAD

**Issue by jasondavis** [varemenos/codemagic#76]
I tried 

- cloning the Git repo to my dev server
- running `npm install` which downloaded node modules
-I then ran `grunt` which shows in my terminal window that it runs the task in the grunt file however it doesn't seem to generate any output or do anything toward making a build that I can test.

---

Can someone help me and others....

- Post the install process here so I can get my demo version running ASAP
- Possibbly add the install process to the `README.md` file in the project

--- 

Thanks for any help

**Comment by varemenos** [comment]
I'm sorry but this project isn't maintained. There have been several major changes in the node and npm ecosystem and I don't have that much free time to keep it up to date. For you to be able to run it, you have to upgrade the npm and bower dependencies and then run `grunt dist`.

If you get it working, feel free to send a PR.

**Comment by jasondavis** [comment]
@varemenos thanks for the reply.  For now I copied the compiled JS and CSS file from the demo site.

My plan is to use it  in my bigger project though so I need to add a load and save function where records can save to a MySQL DB and load from it as well.  That is of course if u don't mind?

If I do so I can share my updates

---

## UPDATE

Looking at code now i can see you have already started some of my needed features.

I come from a PHP background so I am in the process of learning NodeJS now so its a bit new to me but of all the code playgrounds yours is the most complete and feature rich so far for my needs so I am hoping to build upon it

**Comment by varemenos** [comment]
Well I made this playground to compete with codepen but I didn't have a backend developer to work with on storing/loading features, plus I started working full time in a startup so my time became really limited.

Feel free to use the code, it's open source anyway. I'm gonna close this issue, if you need anything else, just post it here.
